### ISSUE TITLE
"Generic type 'AggregateQuerySnapshot<T>' requires 1 type argument(s)."

### ISSUE THREAD

**Issue by tdkehoe** [FirebaseExtended/rxfire#88]
My Angular app won't compile with rxfire 6.0.5. The error is

```
Error: node_modules/rxfire/firestore/lite/interfaces.d.ts:8:29 - error TS2314: Generic type 'AggregateQuerySnapshot<T>' requires 1 type argument(s).

 8 export type CountSnapshot = lite.AggregateQuerySnapshot<{
                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 9     count: lite.AggregateField<number>;
   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
10 }, any, DocumentData>;
   ~~~~~~~~~~~~~~~~~~~~~
```

This is with Firebase 9.23.0. I can't get Firebase 10 to work, see my[ StackOverflow question]((https://stackoverflow.com/questions/77024782/what-is-a-firebase-app-no-firebase-app-default-has-been-created-call-i)).

**Comment by msapcili** [comment]
Hello, I encountered with the same issue. 

Temporarily, I've changed my package.json to force it to use 6.0.4.

**Comment by tdkehoe** [comment]
Why is `rxfire` trying to use Firestore Lite? I never imported anything from `firebase/firestore/lite`.

**Comment by msapcili** [comment]
Same issue, I temporarily fixed it by forcing it to 6.0.4.

**Comment by igoraugustynski** [comment]
Same issue here while using @angular/fire - fixed by installing rxfire 6.0.4 too.

**Comment by hvma411** [comment]
Same issue here with @angular/fire but in my case installing rxfire 6.0.4 didn't help. I tried to install 6.0.3 because this was my previous version in package-lock but it didn't help too so I had to restore my whole previous package-lock where I use rxfire 6.0.3, so probably some other package makes issue too

**Comment by rgant** [comment]
I think the issue here is that [rxfire@6.0.4](https://github.com/FirebaseExtended/rxfire/blob/df3b56868b900a85554bbbdcbff90e304771d184/firestore/lite/interfaces.ts#L9) introduced a breaking change and now _requires_ [firebase@10](https://github.com/firebase/firebase-js-sdk/blob/b58a617f007a4ea2ffe82bc5b9c8ca9a7b7853d9/packages/firestore/src/lite-api/aggregate_types.ts#L74) to function. So sticking to [rxfire@6.0.3](https://github.com/FirebaseExtended/rxfire/blob/83a366fc52e2de7216f9e24e3c2388a00233efc3/firestore/lite/interfaces.ts#L6) with [firebase@9](https://github.com/firebase/firebase-js-sdk/blob/74c3bfbfb64ae62f895e0e5c831b5584f70f6292/packages/firestore/src/lite-api/aggregate_types.ts#L74) is the solution.

**Comment by msapcili** [comment]
> I think the issue here is that [rxfire@6.0.4](https://github.com/FirebaseExtended/rxfire/blob/df3b56868b900a85554bbbdcbff90e304771d184/firestore/lite/interfaces.ts#L9) introduced a breaking change and now _requires_ [firebase@10](https://github.com/firebase/firebase-js-sdk/blob/b58a617f007a4ea2ffe82bc5b9c8ca9a7b7853d9/packages/firestore/src/lite-api/aggregate_types.ts#L74) to function. So sticking to [rxfire@6.0.3](https://github.com/FirebaseExtended/rxfire/blob/83a366fc52e2de7216f9e24e3c2388a00233efc3/firestore/lite/interfaces.ts#L6) with [firebase@9](https://github.com/firebase/firebase-js-sdk/blob/74c3bfbfb64ae62f895e0e5c831b5584f70f6292/packages/firestore/src/lite-api/aggregate_types.ts#L74) is the solution.
> 
> Adding this override to package.json resolves the issue for me:
> 
> ```json
> {
>   "dependencies": {
>     "@angular/fire": "~7.6.1"
>   }
>   "overrides": {
>     "@angular/fire@~7.6.1": {
>       "rxfire@^6.0.0": "6.0.3"
>     }
>   }
> }
> ```

I had commented about my temporary fix by forcing my app to use 6.0.4 but this is more reliable solution. 

I was getting unexpected firebase integration errors such as "FirebaseError: Firebase: No Firebase App '[DEFAULT]' has been created - call initializeApp() first (app/no-app)". Then I tried to force 6.0.3 and these errors are also solved.

Thanks rgant.

**Comment by eyoeldefare** [comment]
This seems to be happening if you're using Firebase SDK Version < 10.
I was having this problem when I was using it with ` Firebase SDK version 9.23.0` and then I updated the `Firebase SDK to version 10.5.2` and the problem went away. 
This means that the issue is with `rxfire` module that failed to be backward compatible to its complimentary Firebase SDK Version, specifically speaking in respect to the `AggregateQuerySnapshot` class that expects 2 different types of data for the 2 versions, hence the error.

`export type CountSnapshot = lite.AggregateQuerySnapshot<{
    count: lite.AggregateField<number>;
}, any, DocumentData>;` This is only compatible with Firebase SDK versions >10 as it expects 3 generic type datas and failed to be compatible with versions less than 10 that only expect 1 generic type data for `AggregateQuerySnapshot`.

**Comment by rgant** [comment]
@eyoeldefare See the overrides necessary: https://github.com/FirebaseExtended/rxfire/issues/88#issuecomment-1715851191

**Comment by Steve-from-Memphis** [comment]
> ```json
>   "overrides": {
>     "@angular/fire@~7.6.1": {
>       "rxfire@^6.0.0": "6.0.3"
>     }
>   }
> ```

I tried this, I get Override for @angular/fire@^7.6.1 conflicts with direct dependency error when I perform npm install

**Comment by rgant** [comment]
@Steve-from-Memphis 
> I tried this, I get Override for @angular/fire@^7.6.1 conflicts with direct dependency error when I perform npm install

Your `"dependency": { "@angular/fire": "`version` must match the override version.
